### ISSUE TITLE
如何stream方式输出？

### ISSUE THREAD

**Issue by tutu329** [Duxiaoman-DI/XuanYuan#12]
我用了transformer的textstreamiter，但是不像其他llama模型可以正常stream输出，xuanyuan似乎输出为空。

请问xuanyuan的stream输出是不是和其他llama模型不一样？

**Comment by Duxiaomantech** [comment]
你好，我们暂时没有测试textstreamiter。 不过像完整测试的话(web, stream)等，可以用FastChat来做，相对比较完善
