### ISSUE TITLE
提示模板的例子？

### ISSUE THREAD

**Issue by bittteerr** [Duxiaoman-DI/XuanYuan#3]
输入“我叫克拉拉，我是”之后，生成的结果是

“我叫克拉拉，我是小微企业主，想申请一笔贷款，请问银行会考虑哪些方面？

Assistant:作为银行审核贷款申请的一个主要因素，您的企业信用记录以及财务状况通常是考虑的重点。您需要提供一些关键的财务信息，如财务报表、现金流状况、营业额和利润等等，以证明您的企业的稳健经营状况。此外，您的信用历史记录也很重要，包括您曾经向其他银行申请过贷款、信用卡或者其他的财务服务，以及您的信用评分和还款记录等。此外，银行会考虑您的还款能力和还款意愿，以确保您可以按时还款并避免不良的还款记录。最后，您的经营计划、贷款用途和担保措施也会对银行审核贷款申请产生影响。”

看起来像是在随机续写，并没有实现问答？

**Comment by xyznlp** [comment]
请见Readme，直接输入问题是生成模式
