### ISSUE TITLE
请问训练轩辕的千亿大模型需要多少GPU资源？

### ISSUE THREAD

**Issue by tangsipeng** [Duxiaoman-DI/XuanYuan#4]
1、如题，论文中只看到用了A100和分布式训练。没有透露实际资源。能否说明？
2、另外，请教一下全量参数训练和一些节约资源的训练方式，如P-turning、Lora等实际使用上的区别和考虑？

**Comment by xyznlp** [comment]
建议使用全量训练，全量训练的最低配置是9台8卡机器。

**Comment by tkone2018** [comment]
@xyznlp  你好，指令微调也是建议全量训练是吗

**Comment by xyznlp** [comment]
@tkone2018 是的，不过资源有限也可以尝试其他训练方式

**Comment by aiolosgs** [comment]
@xyznlp 您好，请问一下论文里边的176B的模型训练了多久呢？
