### ISSUE TITLE
金融评测缺少LLaMA-2-70B的对比

### ISSUE THREAD

**Issue by young-chao** [Duxiaoman-DI/XuanYuan#9]
你好，在本工作中金融评测部分虽然选择了许多当前具备代表性的多个开源和可访问模型进行评测，但是并没有看到LLaMA-2-70B模型（而LLaMA-2-7B、13B都有）的评测结果，这是令人诧异的。因为，XuanYuan-70B是基于LLaMA-2-70B继续训练的，从消融研究的角度来看，LLaMA-2-70B的评测是必不可少的。所以想了解这个评测的缺失是否有特殊的原因？

**Comment by Duxiaomantech** [comment]
您好，感谢指出。Llama2-70b模型的评测我们补充上，这个缺失是因为意外遗漏，没有特殊原因哈
